import '@/styles/globals.scss'
import Head from 'next/head'
import type { AppProps } from 'next/app'
import { Work_Sans } from '@next/font/google'

const workSans = Work_Sans({ subsets: ['latin'], display: 'swap' })


export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <style jsx global>
                {`
                html {
                    font-family: ${workSans.style.fontFamily};
                }
            `}
            </style>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Component {...pageProps} />
        </>
    )

}
